#+title: Посібник автентичного буддизму

* Original
- https://www.shobogenzo.net/index.php/text/handbook-of-authentic-buddhism/

* Вступ
Що таке автентичний буддизм? Автентичний буддизм - це буддизм, який був заснований Буддою Гаутама, і був переданий через традиції Теравада і Махаяна, майстра Нагарджуну, Майстра Бодхідхарму, китайський Буддизм, Майстра Догена і до нас. Кажуть, що дуже складно пояснити буддизм словами. І можливо це правда. Але якщо ми не будемо пояснювати щось словами, то може бути неможливо для когось пояснити це іншим. Тому я б хотів стати перед таким важким випробуванням, а саме пояснити Аутентичний буддизм словами.

* Стати буддистом
Останнім часом не так масово, але напочатку ставання буддистом ми маємо церемонію отримування буддійських настанов від вчителя буддизму. Отримуючи настанови ми стаємо буддистами вперше, і потім починаємо буддистське життя. Для того, щоб зробити цей опис біль конкретним, я хочу розпочати пояснення з цього конкретного факту. В церемонії, вчитель передає учню(учениці) шістнадцять настанов. Настанови розділені на три групи:
1. Три вклоніння
   1. Вклоніння Будді
   2. Вклоніння Дхармі
   3. Вклоніння Сангха
2. Три загальних настанови
   1. Дотримання правил
   2. Дотримання Дхарми
   3. Спасіння всіх живих істот
3. Десять фундаментальних настанов
   1. Не знищуй життя
   2. Не кради
   3. Не прагни зайвого
   4. Не бреши
   5. Не живи, продаючи алкоголь
   6. Не обсговорюй невдачі буддійських священників (священниць), ченців (черниць) і мирян
   7. Не хвали себе, не звинувачуй інших
   8. Don't be sparing of buddhist teachings or other things
   9. Не ставай злим
   10. Не зловживай тринадцятьма вищими цінностями

* Об'єкти поклоніння
Я цитую буддійські настанови тому, що знаходжу це дуже хорошим методом дізнатись про об'єкти релігії для осягнення фнудаментальної ідеї кожної релігії. І у випадку з буддизмом можна побачити першу групу настанов: три вклоніння. На мою думку, через дослідження сенсів трьох вклоніннь ми можемо побачити контури буддизму. Три вклоніння - це вклоніння Будді, вклоніння Дгармі і вклоніння Сангхі.
